name: Code Quality

on:
  workflow_call:

jobs:
  lint-and-sast:
    name: Flake8 + Bandit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install flake8 bandit
      - run: flake8 app.py --max-line-length=100
      - run: bandit -r app.py -s B104
