name: Flask Main CICD Pipeline

on: 
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  security-events: write
  
jobs:
  ci:
    uses: ./.github/workflows/docker-build-push.yml
    secrets: inherit

  cd:
    needs: ci
    uses: ./.github/workflows/self-hosted-deploy.yml
    secrets: inherit
