name: Python matrix

on:
  pull_request:

  push:
    branches: [main]
  workflow_dispatch: 

jobs:
  validate:
  
    name: Python ${{ matrix.python-version }}
    
    strategy:
      matrix:
        python-version: ["3.9","3.10","3.11","3.12","3.13"]
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt

      - name: Python Lint
        run: flake8 app.py
